### ISSUE TITLE
ChhoeTaigi_TaioanSitbutMialui.csv 有 oong

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#1]
`214	Oong7-lai5	Ō͘ng-lâi	Oong7-lai5	Ōong-lâi	？萊`

https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/blob/master/ChhoeTaigiDatabase/20180630-194713/ChhoeTaigi_TaioanSitbutMialui.csv#L215

原始圖檔確實是 oong
http://ip194097.ntcu.edu.tw/memory/TGB/thak.asp?id=59&page=144

敢愛分原始檔，校正後的版本？

**Comment by shiami** [comment]
To-siā, góa ē kap sò͘-ūi-hòa thoân-tūi koh thó-lūn.

**Comment by shiami** [comment]
Fixed. 02e7647b3db0c35854b48f2ada1cd1f3251defcb
