### ISSUE TITLE
詞條資料錯誤回報－Embree台語辭典

### ISSUE THREAD

**Issue by pcki** [ChhoeTaigi/ChhoeTaigiDatabase#10]
ChhoeTaigi_EmbreeTaigiSutian.csv

調符調號拍字重耽去：

535,âng-ko͘-lí-hi**５**,ang5-koo-li2-hi**５**,âng-koo-lí-hi**５**,ang5-koo-li2-hi**５**,"N ",bé,,金線紅姑魚,"a fish of the seabream family, Nemipterus virgatus",

6353,chhiáⁿ,chhia2nn,tshiánn,tshia2nn,"IE ",,,請,"Please!, Please… ",
6354,chhiáⁿ,chhia2nn,tshiánn,tshia2nn,"V ",,,請,"invite, request, treat to (dinner, cigarette, etc)",
6355,chhiáⁿ,chhia2nn,tshiánn,tshia2nn,"V ",,,請,pay for (a dinner or entertainment),
6356,chhiáⁿ,chhia2nn,tshiánn,tshia2nn,"V ",,,請,"engage (teacher, manager, etc)",
6357,chhiáⁿ,chhia2nn,tshiánn,tshia2nn," ",,,請客,"invite a guest, pay for (the dinner or entertainment)",
6358,chhiáⁿ 1í,chhia2nn 1i2,tshiánn 1í,tshia2nn 1i2,"IE ",,to-to chí-kàu,請你多多指教,"How do you do! (polite response to an introduction, literally ""Please give me plenty f instruction)",
6359,chhiáⁿ0mn̄g,chhia2nn0mng7,tshiánn0mn̄g,tshia2nn0mng7,"V ",,,請問,"ask (a question, politely)",
6360,chhiáⁿ0mn̄g,chhia2nn0mng7,tshiánn0mn̄g,tshia2nn0mng7,"IE ",,,請問,"May I ask (a question), Excuse me (before a question)",
6361,chhiáⁿ-toh,chhia2nn-toh,tshiánn-toh,tshia2nn-toh,"VO ",,,請赴宴會,invite (some one) to a feast,
6362,chhiáⁿ-thiap,chhia2nn-thiap,tshiánn-thiap,tshia2nn-thiap,"N ",,tiuN,請帖,"invitation card ",

id 6358 "l" 拍做 "1"

**Comment by pcki** [comment]
chhián -> chhiáⁿ：

23790,pài-chhián,pai3-chhian2,pài-tshián,pai3-tshian2,"V ",,,拜請,give a ceremonial invitation,
24564,pek-chhián,pek-chhian2,pik-tshián,pik-tshian2,"V ",,,逼請,urge an invitation on (someone),
26998,saⁿ-chhián,sann-chhian2,sann-tshián,sann-tshian2,"V ",,,相請,treat each other (to a meal),

**Comment by shiami** [comment]
已經修正--ah，ló͘-la̍t。

https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/tree/20181020-153604/ChhoeTaigiDatabase
