### ISSUE TITLE
Kian-gi mai u si-kan hit tsan tsu-liau-giap

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#13]
Kian-gi mai u si-kan hit tsan tsu-liau-giap, in-ui
- Na koo-ting soo-tsai, thing-sik e-tang tsu-tong lai Github liah, bo su-iau phuann-tuan tong-an e bang-tsi ti toh.
- Ku e pan-pun, ing `git checkout` tshue khah tho-tong.
- King-sin e si-kan khuann `git log` to ho.

### Kian-gi
```
ChhoeTaigiDatabase/
    ├── ChhoeTaigi_EmbreeTaigiSutian.csv
    ├── ChhoeTaigi_iTaigiHoataiSutian.csv
    ├── ChhoeTaigi_KamJitian.csv
    ├── ChhoeTaigi_KauiokpooTaigiSutian.csv
    ├── ChhoeTaigi_MaryknollTaiengSutian.csv
    ├── ChhoeTaigi_TaibunHoabunSoanntengSutian.csv
    ├── ChhoeTaigi_TaijitToaSutian.csv
    ├── ChhoeTaigi_TaioanPehoeKichhooGiku.csv
    ├── ChhoeTaigi_TaioanSitbutMialui.csv
    └── lomaji_search_table
        ├── ChhoeTaigi_iTaigiHoataiSutian.csv
        ├── ChhoeTaigi_KauiokpooTaigiSutian.csv
        ├── ChhoeTaigi_TaibunHoabunSoanntengSutian.csv
        ├── ChhoeTaigi_TaijitToaSutian.csv
        └── ChhoeTaigi_TaioanPehoeKichhooGiku.csv
```

### Guan-pun Keng-sin-tsing
```
ChhoeTaigiDatabase/
└── 20180803-024253
    ├── ChhoeTaigi_EmbreeTaigiSuTian.csv
    ├── ChhoeTaigi_iTaigiHoaTaiSutian.csv
    ├── ChhoeTaigi_KamJitian.csv
    ├── ChhoeTaigi_KauiokpooTaigiSutian.csv
    ├── ChhoeTaigi_MaryknollTaiEngSuTian.csv
    ├── ChhoeTaigi_TaibunHoabunSoanntengSutian.csv
    ├── ChhoeTaigi_TaiJitToaSuTian.csv
    ├── ChhoeTaigi_TaioanPehoeKichhooGiku.csv
    ├── ChhoeTaigi_TaioanSitbutMialui.csv
    └── lomaji_search_table
        ├── ChhoeTaigi_iTaigiHoaTaiSutian.csv
        ├── ChhoeTaigi_KauiokpooTaigiSutian.csv
        ├── ChhoeTaigi_TaibunHoabunSoanntengSutian.csv
        ├── ChhoeTaigi_TaiJitToaSuTian.csv
        └── ChhoeTaigi_TaioanPehoeKichhooGiku.csv
```

### Guan-pun Keng-sin-au
```
ChhoeTaigiDatabase/
└── 20181010-024726
    ├── ChhoeTaigi_EmbreeTaigiSutian.csv
    ├── ChhoeTaigi_iTaigiHoataiSutian.csv
    ├── ChhoeTaigi_KamJitian.csv
    ├── ChhoeTaigi_KauiokpooTaigiSutian.csv
    ├── ChhoeTaigi_MaryknollTaiengSutian.csv
    ├── ChhoeTaigi_TaibunHoabunSoanntengSutian.csv
    ├── ChhoeTaigi_TaijitToaSutian.csv
    ├── ChhoeTaigi_TaioanPehoeKichhooGiku.csv
    ├── ChhoeTaigi_TaioanSitbutMialui.csv
    └── lomaji_search_table
        ├── ChhoeTaigi_iTaigiHoataiSutian.csv
        ├── ChhoeTaigi_KauiokpooTaigiSutian.csv
        ├── ChhoeTaigi_TaibunHoabunSoanntengSutian.csv
        ├── ChhoeTaigi_TaijitToaSutian.csv
        └── ChhoeTaigi_TaioanPehoeKichhooGiku.csv
```

**Comment by shiami** [comment]
Chú-iàu sī àn-sǹg beh hō͘ it-poaⁿ ê lâng khah hó lī-iōng. Bô o̍h kòe che ê lâng sī khah bô hoat-tō͘ lí-kái.

**Comment by shiami** [comment]
Nā beh án-ne tio̍h ài koh lēng-gōa ta̍k pán pau chò 1 ê ap-sok tóng-àn khǹg--chhut-lâi. Chiah hō͘ it-poaⁿ su-iàu ê lâng khì lia̍h.

**Comment by shiami** [comment]
Koh ū 1 ê būn-tê tio̍h-sī, che keh-sek ū khó-lêng ē it-ti̍t cheng-ka a̍h-sī sûi-sî siu-kái, bē kò͘-tēng.

**Comment by sih4sing5hong5** [comment]
> Chú-iàu sī àn-sǹg beh hō͘ it-poaⁿ ê lâng khah hó lī-iōng. Bô o̍h kòe che ê lâng sī khah bô hoat-tō͘ lí-kái.
> Nā beh án-ne tio̍h ài koh lēng-gōa ta̍k pán pau chò 1 ê ap-sok tóng-àn khǹg--chhut-lâi. Chiah hō͘ it-poaⁿ su-iàu ê lâng khì lia̍h.

Tse e-tang ing `git tag`. Github u the-kiong GUI, ti https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/releases .

> Koh ū 1 ê būn-tê tio̍h-sī, che keh-sek ū khó-lêng ē it-ti̍t cheng-ka a̍h-sī sûi-sî siu-kái, bē kò͘-tēng.

To ka̋ kái bua̋-kín. Thing-sik tsiah-koh kai to-ho. [Kau-tian e tsu-liau](https://github.com/g0v/moedict-data-twblg/tree/master/uni) gun ma si tue i kai.
Gua e thing-sik senn tso [an-ne](https://github.com/Taiwanese-Corpus/hue7jip8/blob/master/%E5%8C%AF%E5%85%A5/management/commands/%E6%95%99%E5%85%B8%E8%A9%9E%E6%A2%9D.py#L21-L24).

**Comment by shiami** [comment]
Bô góa chiah kā pán-pún phiau tī tag hó--a.

**Comment by shiami** [comment]
Góa āu 1-pán chiah chò-hóe siu-kái.

Chit-má ê ūi-tì:
https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/tree/master/ChhoeTaigiDatabase/20181010-024726

Sin ê ūi-tì ē pìⁿ án-ne:
https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/tree/20181010-024726/ChhoeTaigiDatabase/

**Comment by sih4sing5hong5** [comment]
Loo-lat.

**Comment by shiami** [comment]
已經改好--ah。
https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/tree/20181020-033643

**Comment by sih4sing5hong5** [comment]
Lóo-la̍t~~~
