### ISSUE TITLE
Tâi-ji̍t Tōa-sû-tián ê liân-jī-hû būn-tê

### ISSUE THREAD

**Issue by hiankun** [ChhoeTaigi/ChhoeTaigiDatabase#17]
台日典 lāité, "地動" ài iōng "tē tāng" (bô hyphen) chiah chhōe ū. Che sī púnté chuliāukhò͘ ê iânkò͘, m̄koh mā sī pò hō͘ lí chai, khòaⁿ ū káikoat ê hoattō͘ bô.

**Comment by shiami** [comment]
Chiàu Tâi-ji̍t Tōa-sû-tián siá-hoat, pheng-im pō͘-hūn bô tek-pia̍t kì liân-jī hû-hō.
Èng-kai kā choân-pō͘ ê sû tòng-chò sû-cho͘ chhú-lí khah hó.

Ē kái chò choân-pō͘ lóng sī liân-jī-hû, bē ū khang-pe̍h.
Chiah lâi siu-kái.

**Comment by shiami** [comment]
Keng-sin:

1. Tâi-ji̍t Tōa-sû-tián liân-oe̍h kì tī Hàn-jī ê só͘-chai.
2. Chín bāng-chām í-keng ū chi-oān iōng khang-pe̍h lâi chhōe, liân-oe̍h ū--bô lóng chhiau ū.
3. Sòa #2, chu-liāu chiàu goân-chheh, bô koh siu-kái.
