### ISSUE TITLE
台灣白話基礎語句 kah 台灣植物名彙

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#2]
這兩个語料攏有原圖
http://ip194097.ntcu.edu.tw/memory/TGB/thak.asp?id=59
http://ip194097.ntcu.edu.tw/memory/TGB/thak.asp?id=862

我想講，會當分別閣開一个github專案
囥整理好的csv、kah圖檔

若是OK，我會當來準備

**Comment by sih4sing5hong5** [comment]
我整理佇
- https://github.com/Taiwanese-Corpus/Syuniti-Sasaki_1928_List-of-Plants-of-Formosa
- https://github.com/Taiwanese-Corpus/Ko-Chek-hoan-Tan-Pang-tin_1956_Basic-Vocabulary-for-Colloquial-Taiwanese

**Comment by shiami** [comment]
@sih4sing5hong5 Chin ló͘-la̍t.
