### ISSUE TITLE
基礎語句tîng-tânn

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#24]
連字符「-」後壁閬一格無接字！！語句：「chit- ē」
連字符「-」頭前閬一格無接字！！語句：「un -pân」
連字符「-」頭前閬一格無接字！！語句：「kho -ha̍k」
連字符「-」後壁閬一格無接字！！語句：「Khòaⁿ- mî-sat」
連字符「-」後壁閬一格無接字！！語句：「Lia̍h- khì koaiⁿ」
連字符「-」後壁閬一格無接字！！語句：「Nńg- sòaⁿ」
連字符「-」後壁閬一格無接字！！語句：「Nńg- sòaⁿ」
連字符「---」分析器毋知愛按怎處理。語句：「Tat---tio̍h」
連字符「-」後壁閬一格無接字！！語句：「Ū- miâ」

**Comment by shiami** [comment]
Kái hó--ah.
