### ISSUE TITLE
「台灣白話基礎語句」目前kan-na收語詞，iáu無收例句

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#3]
Lai-te e `eng chhiam-ma chhiam khi-lai chiah` le-ku, chit pai ke-ue kam u phah-ji?
![topokcgk_ _109](https://user-images.githubusercontent.com/5996555/43114422-96f46a64-8f31-11e8-8ba9-e309d0339390.png)

**Comment by shiami** [comment]
Í-keng pó͘ liáu.
