### ISSUE TITLE
Hòⁿ-kî ChhoeTaigi tùi 廈英大辭典 ê khòaⁿ-hoat?

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#49]
Chu-liāu:
https://github.com/Taiwanese-Corpus/Carstairs-Douglas_1873_chinese-english-dictionary

Hòⁿ-kî siūⁿ-beh mn̄g khòaⁿ-māi~

**Comment by shiami** [comment]
Beh kóng ōe-thâu tn̂g.
