### ISSUE TITLE
植物名彙資料錯誤

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiDatabase#5]
https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/blob/master/ChhoeTaigiDatabase/20180630-194713/ChhoeTaigi_TaioanSitbutMialui.csv#L1399
```
1398,€,€,€,€,蒲荊,353
```
直接PR抑是？
![tosbbl_ _397](https://user-images.githubusercontent.com/5996555/43127056-152bb62e-8f61-11e8-9bec-4487d64262c5.png)

**Comment by sih4sing5hong5** [comment]
http://ip194097.ntcu.edu.tw/memory/TGB/thak.asp?id=59&page=452
```
1658,Soe3-ho7-lat8-a2,Sòe-hō-la̍t-á,Sue3-ho7-lat8-a2,Suè-hō-la̍t-á,細號拈力仔,408
```
`Sòe-hō-liam-la̍t-á`

http://ip194097.ntcu.edu.tw/memory/TGB/thak.asp?id=59&page=360
```
1245,Ian5-sui,Iân-sui,Ian5-sui,Iân-sui,？荽、蓑,316
```
應該`？荽、？蓑`

http://ip194097.ntcu.edu.tw/memory/TGB/thak.asp?id=59&page=339
```
1159,Ng5-hoe-a2-chhau2,N̂g-hoe-á-chháu,Ng5-hue-a2-tshau2,N̂g-hue-á-tsháu,黃花仔,295
```
`黃花仔草`

**Comment by sih4sing5hong5** [comment]
看按怎恁較方便～～

**Comment by shiami** [comment]
> 1398,€,€,€,€,蒲荊,353
Bô siá Lô-má-jī, ē kā thai tiāu.

Kî-thaⁿ í-keng siu-kái.

**Comment by shiami** [comment]
Fixed. 02e7647b3db0c35854b48f2ada1cd1f3251defcb
