### ISSUE TITLE
教育部辭典字碼更換

### ISSUE THREAD

**Issue by yesleon** [ChhoeTaigi/ChhoeTaigiDatabase#58]
資料庫的教育部辭典中有些條目的台文漢字用支援台文的字型也無法顯示，例如 [gàn](https://chhoe.taigi.info/KauiokpooTaigiSutian/13615)。
教育部辭典網站與萌典等處似乎有更新相關字的字碼，參考：[https://github.com/tauhu-tw/tauhu-taigi](https://github.com/tauhu-tw/tauhu-taigi)。
我有找到一些可更新的漢字如下：

 -> 𫝏
 -> 𬦰
 -> 𪜶
 -> 𫝛
 -> 𫝺
 -> 𫝻
 -> 𫞼
 -> 𫟂
 -> 𰣻

**Comment by shiami** [comment]
已經照今年ê辭典資料更新--ah。
