### ISSUE TITLE
台日大辭典內底ê漢字有ê ē顯示"[ ]"

### ISSUE THREAD

**Issue by shiami** [ChhoeTaigi/ChhoeTaigiDatabase#7]
例：http://taigi.fhl.net/dict/search.php?DETAIL=1&LIMIT=id=49148&dbname=dic&graph=2

用keyword chhōe完全kāng-khoán ê詞ê時，ē chhōe無。
需要kā the̍h掉。

**Comment by shiami** [comment]
Tī 版本 20181010-024726 已經修正，m̄-koh原始資料無改。

**Comment by pcki** [comment]
網站是m̄是無翻新？網頁版查台日典 iáu 是有 chit ê 問題。
