### ISSUE TITLE
詞條資料錯誤回報－台文華文線頂辭典

### ISSUE THREAD

**Issue by pcki** [ChhoeTaigi/ChhoeTaigiDatabase#9]
ChhoeTaigi_TaibunHoabunSoanntengSutian.csv

有个資料加一个"null"：

23667,hio**null**,,hioo3,,hio**null**,hiòo,,hioo3,,hiòo,是的
23668,hio**null**,,hioo3,,hio**null**,hiòo,,hioo3,,hiòo,是嗎
31152,jia̍t-sim-t**null**g,,jiat8-sim-tng6,,熱心腸,jia̍t-sim-tng,,jiat8-sim-tng6,,熱心腸,熱腸
50754,lô-th**null**,,lo5-tho1,,囉叨,lô-tho,,lo5-tho1,,囉叨,叨叨
50755,lô-th**null**,,lo5-tho1,,囉叨,lô-tho,,lo5-tho1,,囉叨,叨嘮
74397,t**null**k-mi̍h,,tak6-mih8,,濁物,tak-mi̍h,,tak6-mih8,,濁物,廢物

**Comment by shiami** [comment]
已經修改好--ah。
https://github.com/ChhoeTaigi/ChhoeTaigiDatabase/tree/20181020-033643
